package com.bachir.customer;

/**
 * A record class that represents a customer registration request.
 * This class is used to collect user information from a client-facing operation, possibly a form submission or an API request,
 * that wishes to register a new customer. Being a record, it offers an immutable data structure,
 * which means that once an instance is created, it cannot be altered.
 *
 * Attributes:
 * - name: The full name of the customer wishing to register.
 * - email: The email address of the customer, used for identification and possibly communication.
 * - age: The age of the customer. Depending on business rules, this could be used for validation.
 *
 * Usage example:
 * CustomerRegistrationRequest registrationRequest = new CustomerRegistrationRequest("Jane Doe", "jane.doe@example.com", 25);
 * // ...process registrationRequest object, possibly passing it to a service that handles customer registration.
 *
 * Note:
 * - Since this is a record, the class implicitly has a final field for each attribute,
 *   a public constructor with parameters matching the attributes, and getters for each field.
 * - No setter methods are available as records are intended to be immutable data carriers.
 * - The class should be used in situations where data is meant to be transferred and not modified after creation.
 *
 */
public record CustomerRegistrationRequest (
        String name,
        String email,
        Integer age
) {
    // All methods, including the constructor, are generated by the Java compiler.
    // Additional validation logic or methods can be added as needed, especially if
    // you need to validate individual attributes beyond type checking.
}
